# Backend Dockerfile (Golang Gin)
FROM golang:alpine AS builder
WORKDIR /app

RUN apk add --no-cache git

COPY api/go.mod api/go.sum* ./
RUN go mod download || true

COPY api/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM alpine:latest AS runner
WORKDIR /app
RUN mkdir -p /app/data
COPY --from=builder /app/server .


EXPOSE 8080
CMD ["./server"]
